- name: Installer snapd
  package:
    name: snapd
    state: present

- name: Installer Semaphore via Snap
  snap:
    name: semaphore
    state: present

- name: Ajouter l'utilisateur admin à Semaphore
  command: >
    semaphore user add
    --admin
    --login admin
    --name Admin
    --email admin@example.com
    --password 123456
    --config ansible-role-semaphore/files/config.json

- name: Démarrer le service Semaphore
  command: snap start semaphore
