- name: SoftThibault
  hosts: all
  become: true
  tasks:
    - name: Créer un utilisateur pour l'API
      ansible.builtin.user:
        name: apiuser
        comment: "User for running the API"
        create_home: yes

    - name: Mettre à jour les paquets apt
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Installer les dépendances nécessaires
      ansible.builtin.apt:
        name:
          - python3
          - python3-venv
          - git
        state: present

    - name: Cloner le repository gist
      ansible.builtin.git:
        repo: 'https://gist.github.com/thibaultserti/21456f4797100376f67443920e5d5145.git'
        dest: /opt/mysoftware

    - name: Créer un environnement virtuel Python
      ansible.builtin.command:
        cmd: python3 -m venv /opt/mysoftware/venv

    - name: Installer les dépendances Python
      ansible.builtin.pip:
        requirements: /opt/mysoftware/requirements.txt
        virtualenv: /opt/mysoftware/venv

    - name: Créer le fichier de service systemd pour l'API
      ansible.builtin.template:
        src: templates/mysoftware-api.service.j2
        dest: /etc/systemd/system/mysoftware-api.service

    - name: Activer le service systemd pour l'API
      ansible.builtin.systemd:
        name: mysoftware-api
        state: started
        enabled: yes

    - name: Lancer l'API avec Uvicorn
      ansible.builtin.shell: source /opt/mysoftware/venv/bin/activate && uvicorn main:app --reload
      args:
        chdir: /opt/mysoftware
      async: 1
      poll: 0
